
name: Update LLM Leaderboard

on:
  schedule:
    # Runs every 12 hours at 00:00 and 12:00 UTC
    - cron: '0 0,12 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas pyyaml lxml

    - name: Scrape latest leaderboard data
      run: |
        python scripts/scrape-leaderboard.py
        echo "Scraping completed"
      continue-on-error: false
      
    - name: Generate updated README
      run: |
        python scripts/generate-readme.py
        echo "README generation completed"
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md data/leaderboard.json
        git commit -m "🤖 Auto-update LLM leaderboard - $(date '+%Y-%m-%d %H:%M UTC')"
        git push
        
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'LLM Leaderboard Update Failed',
            body: 'The automated leaderboard update failed. Please check the workflow logs for details.'
          })
